export const Testi = {
  // --- AUTENTICAZIONE (Login & Register) ---
  auth: {
    loginTitle: "Bentornato",
    registerTitle: "Crea Account",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    usernamePlaceholder: "Username",
    birthDatePlaceholder: "Data di nascita (es. 09-09-1997)",
    loginButton: "Accedi",
    registerButton: "Registrati",
    linkToRegister: "Non hai un account? Registrati",
    linkToLogin: "Hai già un account? Accedi",
    errorFillAll: "Compila tutti i campi",
    errorInvalidDate: "Formato data non valido. Usa DD-MM-YYYY (es. 09-09-1997)",
    errorLogin: "Errore durante il login",
    errorRegister: "Errore durante la registrazione",
  },

  // --- AREA PRIVATA ---
  privato: {
    oggiTitle: "Oggi",
    calendarioTitle: "Calendario",
    nessunTaskOggi: "Nessun task per oggi",
    sezioneEventiFissi: "I Tuoi Eventi Fissi",
    nessunEventoFisso: "Crea un evento fisso per inserirlo velocemente nel calendario.",
    inserisciInDate: "Inserisci in",
    inserisciDateSuf: "date",
    compleannoTitolo: "Tanti Auguri!",
    compleannoTesto: "Oggi è il tuo compleanno! Goditi questa giornata.",
    alertSvuotaOggi: "Sei sicuro di voler svuotare tutti i task di oggi?",
    alertSvuotaCalendario: "Sei sicuro di voler svuotare tutte le caselle del calendario dai task?",
    alertSvuotaFissi: "Sei sicuro di voler svuotare l'intera lista dei task fissi?",
  },

  // --- AREA CONDIVISA ---
  condiviso: {
    gestioneTitle: "Gestione",
    oggiTitle: "Oggi",
    calendarioTitle: "Calendario",
    nessunCalendario: "Nessun calendario collegato. Vai nella sezione Gestione.",
    sezioneITuoiCalendari: "I Tuoi Calendari Condivisi:",
    creaNuovoTitle: "Crea Nuovo Calendario",
    nomeCalendarioPlaceholder: "Nome calendario (es. Casa, Lavoro...)",
    btnCreaGenera: "Crea e Genera OTP",
    uniscitiTitle: "Unisciti con Codice OTP",
    otpPlaceholder: "Incolla qui il codice OTP...",
    btnUnisciti: "Unisciti",
    otpLabel: "Codice OTP (Tocca per copiare):",
    membri: "Membri:",
    nessunTaskOggi: "Nessun task condiviso per oggi",
    sezioneEventiFissi: "I Tuoi Eventi Fissi (Personali)",
    nessunEventoFisso: "Crea un evento fisso personale per inserirlo velocemente in più date.",
    alertSvuotaOggi: 'Sei sicuro di voler svuotare tutti i task di oggi per il calendario',
    alertSvuotaCalendario: 'Vuoi svuotare interamente il calendario',
    alertEsciCalendario: "Vuoi USCIRE da questo calendario condiviso? Non vedrai più i suoi eventi.",
    alertEliminaCalendario: "Sei il proprietario di questo calendario. Vuoi ELIMINARE definitivamente il calendario e tutti i suoi task per tutti i membri?",
  },

  // --- COMPONENTI GLOBALI E MODALI ---
  modali: {
    tuttoIlGiorno: "Tutto il giorno",
    oraInizio: "Ora Inizio",
    oraFine: "Ora Fine",
    descrizioneOptional: "Descrizione (Opzionale)",
    descrizionePlaceholder: "Aggiungi dettagli...",
    urlOptional: "URL (Opzionale)",
    urlPlaceholder: "https://...",
    colore: "Colore",
    titoloPlaceholder: "Titolo *",
    importaFisso: "Importa da Evento Fisso:",
    btnAnnulla: "Annulla",
    btnSalva: "Salva",
    btnEsci: "Esci",
    btnChiudi: "Chiudi",
    nuovoTaskCondiviso: "Nuovo Task Condiviso",
    modificaTaskCondiviso: "Modifica Task Condiviso",
    nuovoTaskPrivato: "Nuovo Task",
    modificaTaskPrivato: "Modifica Task",
    nuovoEventoFisso: "Nuovo Evento Fisso",
    modificaEventoFisso: "Modifica Evento Fisso",
    nessunEventoData: "Nessun evento in questa data.",
    erroreInizioFine: "La data di inizio non può superare la fine",
    erroreConflittoDate: "Questo evento è già presente nelle date:",
    alertEliminaTask: "Vuoi davvero eliminare questo task?",
  },

  // --- MESSAGGI DI SISTEMA ---
  alert: {
    otpCopiato: "Codice OTP copiato negli appunti!",
    otpCode: "Codice OTP:",
    erroreLink: "Impossibile aprire il link. Verifica che l'URL sia corretto (es: https://...)",
  }
};